# Generated by Django 4.0.9 on 2023-06-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('and', 'Any'), ('or', 'All')], default='and', max_length=5)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='matcher.response', verbose_name='')),
            ],
        ),
    ]
