# Generated by Django 4.0.9 on 2023-06-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='MessageResponse',
        ),
    ]
